explore_costmap:
    global_frame: map
    robot_base_frame: base_link
    update_frequency: 1.0
    publish_frequency: 1.0
    static_map: true
    rolling_window: false
    resolution: 0.05
    track_unknown_space: true
    plugins:
        - {name: external, type: "costmap_2d::StaticLayer"}
        - {name: polygon_layer,    type: "polygon_layer::PolygonLayer"}
        - {name: obstacles_laser, type: "costmap_2d::ObstacleLayer"}
        - {name: inflation, type: "costmap_2d::InflationLayer"}

    polygon_layer:
        resize_to_polygon: true