global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 10
  publish_frequency: 10
  width: 100.0
  height: 100.0
  resolution: 0.05
  origin_x: -20.0
  origin_y: -20.0
  static_map: false
  rolling_window: true

  plugins:
    - { name: obstacles_layer, type: "costmap_2d::ObstacleLayer" }
    - { name: inflater_layer, type: "costmap_2d::InflationLayer" }

  obstacles_layer:
    observation_sources: scan
    scan: { sensor_frame: front_laser, data_type: LaserScan, topic: front/scan, marking: true, clearing: true, min_obstacle_height: -2.0, max_obstacle_height: 2.0, obstacle_range: 10.0, raytrace_range: 10.0 }
